Repository spring-cloud/spring-cloud-aws, pull requests merged in 2020-11, with the labels that each got.

#697 Add Github action to build docs and upload them to S3.
  .github/workflows/upload-docs.yml
  docs/pom.xml
Labels: component: infrastructure, type: maintenance

#706 Determine 'content-type' from S3 location
  spring-cloud-aws-core/src/main/java/org/springframework/cloud/aws/core/io/s3/SimpleStorageNameUtils.java
  spring-cloud-aws-core/src/main/java/org/springframework/cloud/aws/core/io/s3/SimpleStorageProtocolResolver.java
  spring-cloud-aws-core/src/main/java/org/springframework/cloud/aws/core/io/s3/SimpleStorageResource.java
  spring-cloud-aws-core/src/test/java/org/springframework/cloud/aws/core/io/s3/SimpleStorageNameUtilsTest.java
  spring-cloud-aws-core/src/test/java/org/springframework/cloud/aws/core/io/s3/SimpleStorageResourceTest.java
Labels: component: core, component: s3, type: enhancement

#707 Escalate visibility of isQueueRunning method
  spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/listener/SimpleMessageListenerContainer.java
Labels: component: sqs, type: enhancement

#716 Improve tests to use ApplicationContextRunner
  spring-cloud-aws-autoconfigure/src/test/java/org/springframework/cloud/aws/autoconfigure/context/ContextInstanceDataAutoConfigurationTest.java
  spring-cloud-aws-autoconfigure/src/test/java/org/springframework/cloud/aws/autoconfigure/context/ContextResourceLoaderAutoConfigurationTest.java
  spring-cloud-starter-aws-secrets-manager-config/src/test/java/org/springframework/cloud/aws/autoconfigure/secretsmanager/AwsSecretsManagerBootstrapConfigurationTest.java
Labels: component: secrets-manager

#719 Refactor docs
  docs/src/main/asciidoc/cloudformation.adoc
  docs/src/main/asciidoc/cloudwatch.adoc
  docs/src/main/asciidoc/elasticache.adoc
  docs/src/main/asciidoc/parameter-store.adoc
  docs/src/main/asciidoc/rds.adoc
  docs/src/main/asciidoc/s3.adoc
  docs/src/main/asciidoc/secrets-manager.adoc
  docs/src/main/asciidoc/ses.adoc
  docs/src/main/asciidoc/sns.adoc
  docs/src/main/asciidoc/spring-cloud-aws.adoc
  docs/src/main/asciidoc/sqs.adoc
Labels: type: documentation

#720 Add release workflow
  .github/workflows/release.yml
  pom.xml
Labels: type: dependency-upgrade, waiting-for-triage

#680 Add cognito integration
  spring-cloud-aws-autoconfigure/pom.xml
  spring-cloud-aws-autoconfigure/src/main/java/org/springframework/cloud/aws/autoconfigure/security/CognitoAuthenticationAutoConfiguration.java
  spring-cloud-aws-autoconfigure/src/main/java/org/springframework/cloud/aws/autoconfigure/security/CognitoAuthenticationProperties.java
  spring-cloud-aws-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  spring-cloud-aws-autoconfigure/src/main/resources/META-INF/spring.factories
  spring-cloud-aws-autoconfigure/src/test/java/org/springframework/cloud/aws/autoconfigure/security/CognitoAuthenticationAutoConfigurationTest.java
Labels: component: cognito, type: feature

#727 Disable CloudFormation support by default.
  docs/src/main/asciidoc/cloudformation.adoc
  spring-cloud-aws-autoconfigure/pom.xml
  spring-cloud-aws-context/pom.xml
  spring-cloud-aws-core/pom.xml
  spring-cloud-aws-integration-test/pom.xml
Labels: type: enhancement

#726 Add ability to pass AmazonS3 to SimpleStorageProtocolResolver via constructor.
  spring-cloud-aws-core/src/main/java/org/springframework/cloud/aws/core/io/s3/SimpleStorageProtocolResolver.java
Labels: component: s3, type: bug

#728 Fix ClassNotFoundException caused by `SesAutoConfiguration`.
  spring-cloud-aws-autoconfigure/src/main/java/org/springframework/cloud/aws/autoconfigure/mail/SesAutoConfiguration.java
  spring-cloud-aws-autoconfigure/src/main/java/org/springframework/cloud/aws/autoconfigure/mail/SimpleEmailAutoConfiguration.java
Labels: component: ses

#729 Upgrade AWS SDK to 1.11.907
  spring-cloud-aws-dependencies/pom.xml
Labels: component: core, type: dependency-upgrade

#730 Disable ContextInstanceDataAutoConfiguration by default.
  docs/src/main/asciidoc/_configprops.adoc
  docs/src/main/asciidoc/spring-cloud-aws.adoc
  spring-cloud-aws-autoconfigure/src/main/java/org/springframework/cloud/aws/autoconfigure/condition/ConditionalOnAwsCloudEnvironment.java
  spring-cloud-aws-autoconfigure/src/main/java/org/springframework/cloud/aws/autoconfigure/context/ContextInstanceDataAutoConfiguration.java
  spring-cloud-aws-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  spring-cloud-aws-autoconfigure/src/test/java/org/springframework/cloud/aws/autoconfigure/context/ContextInstanceDataAutoConfigurationTest.java
Labels: component: core, type: enhancement

#731 Document required IAM permissions for S3
  docs/src/main/asciidoc/s3.adoc
Labels: type: documentation

#733 Document required IAM permissions for SES
  docs/src/main/asciidoc/ses.adoc
Labels: type: documentation

#737 Fixing docs
  docs/src/main/asciidoc/ses.adoc
Labels: type: documentation
